# build stage
FROM node:lts-alpine AS build-stage

RUN apk update && apk add git

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN mv .env.escaner2030 .env.production
RUN npm run build

# production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
