version: "3.3"
services:
  escaner-frontend:
    build: .
    container_name: escaner-frontend
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - 8070:80
    depends_on:
      - mongo
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
