version: '3.3'
services:
  scanner-frontend:
    image: politicalwatch/scanner2030:latest
    container_name: scanner-frontend
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
