const messages = {
  en: {
    common: {
      header: {
        brand: 'Scanner2030',
      },
      menu: {
        scanner: 'Scanner',
        about: 'About',
      },
      footer: {
        developedBy: 'Developed by',
        supportedBy: 'Supported by',
      },
      cookies: {
        info: 'Este sitio usa cookies para asegurarte la mejor experiencia web.',
        accept: 'Accept',
        decline: 'Decline',
      },
    },
    about: {
      content: `<p>
      <b>Escáner2030</b> es una innovadora herramienta que permite
      identificar y etiquetar de manera automática textos y documentos en
      clave de Agenda 2030 y sus 17 Objetivos de Desarrollo Sostenible.
    </p>
    <h4>¿Cómo funciona?</h4>
    <p>
      <b>Escáner2030</b> dispone de una base de conocimiento compuesta por
      terminología asociada a los ODS que permite, mediante un proceso
      automático de etiquetado masivo, clasificar las expresiones de los
      textos introducidos, de acuerdo con su relación con los ODS y sus
      respectivas metas.
    </p>
    <p>
      Una vez realizado este etiquetado, y a través de una interfaz
      intuitiva, atractiva y accesible, se ofrece toda la información en
      un formato reutilizable. Esto permite que los y las usuarias puedan
      cargar sus textos y/o documentos para realizar un escaneo adaptado a
      sus necesidades.
    </p>
    <h4>¿Puede adaptarse a otros países?</h4>
    <p>
      Sí, la herramienta ha sido diseñada para que su adaptación sea
      posible. La tecnología utilizada en <b>Escáner2030</b> está
      construida utilizando software libre y código abierto, lo cual
      permite que su adaptación a otros países o a otros contextos
      (académicos, administración pública, entre otros) sea posible de
      manera rápida y respondiendo a las necesidades propias de cada
      contexto.
    </p>
    <h4>¿Quiénes somos?</h4>
    <p>
      <b>Escáner2030</b> es un proyecto de
      <a href="https://politicalwatch.es" target="_blank"
        >Political Watch</a
      >, un think-and-do tank español. La misión de Political Watch es
      generar, allá donde trabajamos, unas condiciones favorables para el
      diseño, adopción e implementación de políticas públicas que
      promuevan una sociedad más justa, equitativa y sostenible. Political
      Watch desarrolla tecnologías innovadoras que permiten automatizar
      los procesos de búsqueda de información y actividad política
      relacionada con el desarrollo sostenible y que ofrecen acceso a esta
      información de forma pública, directa y gratuita.
    </p>
    <h4>¿Quiénes nos han apoyado?</h4>
    <p>
      Para el desarrollo de este proyecto ha sido fundamental la
      colaboración de dos entidades: la
      <a
        href="http://www.exteriores.gob.es/Portal/es/Ministerio/SecretariosDeEstado/SecretariaDeEstadoCooperacionInternacional/Paginas/Inicio.aspx"
        target="_blank"
        >Secretaría de Estado de Cooperación Internacional</a
      >
      del Ministerio de Asuntos Exteriores, Unión Europea y Cooperación
      del Gobierno de España y
      <a href="https://www.actua.ad/es/" target="_blank"
        >Actua Innovació</a
      >, hub tecnológico y de conocimiento, que promueve la investigación
      y la innovación en Andorra.
    </p>
    <h4>¿De dónde venimos?</h4>
    <p>
      <b>Escáner2030</b> es una adaptación de
      <a href="https://tipiciudadano.es" target="_blank">TiPi Ciudadano</a
      >, una herramienta digital implementada en España desde 2015, que
      monitoriza toda la actividad parlamentaria del Congreso de los
      Diputados en relación a 23 temáticas ligadas a la lucha contra la
      pobreza y la desigualdad. Otras herramientas desarrolladas por
      Political Watch con la misma tecnología son
      <a href="https://parlamento2030.es" target="_blank"
        >Parlamento2030</a
      >
      y
      <a href="http://ods.congreso.gov.py/" target="_blank"
        >Congreso2030Py</a
      >.
    </p>`,
    },
    page404: {
      title: 'Page not found',
      body: 'The page you are looking for does not exist.',
      button: 'Go to the home page',
    },
    scanned: {},
    scanner: {
      title: 'Scan any text',
      subtitle:
        'Label and visualise the content of your text in relation to the 2030 Global Goals',
      info: `<p>
      <strong>How does it work?</strong>
      Copy and paste the contents of the text to be analysed in the box shown below or select a file from your computer. Once you have it simply hit the Scan button and enjoy the automatic visualisations generated by the tool.
      </p>
      <p>
      <strong>Scaner 2030</strong>
      is an open access and free use tool that allows you to detect and obtain visualisations of the presence of the different Sustainable Development Goals (SDGs) in any text.
      </p>`,
      form: {
        placeholder: 'Insert the text you want to scan...',
        file: 'Upload a file',
        weight: 'The max file size allowed is 20 MB.',
        button: 'Scan now',
      },
    },
  },
  es: {
    common: {
      header: {
        brand: 'Escáner2030',
      },
      menu: {
        scanner: 'Escáner',
        about: 'Acerca',
      },
      footer: {
        developedBy: 'Desarrollado por',
        supportedBy: 'Con el apoyo de',
      },
      cookies: {
        info: 'Este sitio usa cookies para asegurarte la mejor experiencia web.',
        accept: 'Aceptar',
        decline: 'Rechazar',
      },
    },
    about: {
      content: `<p>
      <b>Escáner2030</b> es una innovadora herramienta que permite
      identificar y etiquetar de manera automática textos y documentos en
      clave de Agenda 2030 y sus 17 Objetivos de Desarrollo Sostenible.
    </p>
    <h4>¿Cómo funciona?</h4>
    <p>
      <b>Escáner2030</b> dispone de una base de conocimiento compuesta por
      terminología asociada a los ODS que permite, mediante un proceso
      automático de etiquetado masivo, clasificar las expresiones de los
      textos introducidos, de acuerdo con su relación con los ODS y sus
      respectivas metas.
    </p>
    <p>
      Una vez realizado este etiquetado, y a través de una interfaz
      intuitiva, atractiva y accesible, se ofrece toda la información en
      un formato reutilizable. Esto permite que los y las usuarias puedan
      cargar sus textos y/o documentos para realizar un escaneo adaptado a
      sus necesidades.
    </p>
    <h4>¿Puede adaptarse a otros países?</h4>
    <p>
      Sí, la herramienta ha sido diseñada para que su adaptación sea
      posible. La tecnología utilizada en <b>Escáner2030</b> está
      construida utilizando software libre y código abierto, lo cual
      permite que su adaptación a otros países o a otros contextos
      (académicos, administración pública, entre otros) sea posible de
      manera rápida y respondiendo a las necesidades propias de cada
      contexto.
    </p>
    <h4>¿Quiénes somos?</h4>
    <p>
      <b>Escáner2030</b> es un proyecto de
      <a href="https://politicalwatch.es" target="_blank"
        >Political Watch</a
      >, un think-and-do tank español. La misión de Political Watch es
      generar, allá donde trabajamos, unas condiciones favorables para el
      diseño, adopción e implementación de políticas públicas que
      promuevan una sociedad más justa, equitativa y sostenible. Political
      Watch desarrolla tecnologías innovadoras que permiten automatizar
      los procesos de búsqueda de información y actividad política
      relacionada con el desarrollo sostenible y que ofrecen acceso a esta
      información de forma pública, directa y gratuita.
    </p>
    <h4>¿Quiénes nos han apoyado?</h4>
    <p>
      Para el desarrollo de este proyecto ha sido fundamental la
      colaboración de dos entidades: la
      <a
        href="http://www.exteriores.gob.es/Portal/es/Ministerio/SecretariosDeEstado/SecretariaDeEstadoCooperacionInternacional/Paginas/Inicio.aspx"
        target="_blank"
        >Secretaría de Estado de Cooperación Internacional</a
      >
      del Ministerio de Asuntos Exteriores, Unión Europea y Cooperación
      del Gobierno de España y
      <a href="https://www.actua.ad/es/" target="_blank"
        >Actua Innovació</a
      >, hub tecnológico y de conocimiento, que promueve la investigación
      y la innovación en Andorra.
    </p>
    <h4>¿De dónde venimos?</h4>
    <p>
      <b>Escáner2030</b> es una adaptación de
      <a href="https://tipiciudadano.es" target="_blank">TiPi Ciudadano</a
      >, una herramienta digital implementada en España desde 2015, que
      monitoriza toda la actividad parlamentaria del Congreso de los
      Diputados en relación a 23 temáticas ligadas a la lucha contra la
      pobreza y la desigualdad. Otras herramientas desarrolladas por
      Political Watch con la misma tecnología son
      <a href="https://parlamento2030.es" target="_blank"
        >Parlamento2030</a
      >
      y
      <a href="http://ods.congreso.gov.py/" target="_blank"
        >Congreso2030Py</a
      >.
    </p>`,
    },
    page404: {
      title: '¿Te has perdido?',
      body: 'Regresa a la página de inicio para encontrar lo que realmente estás buscando.',
      button: 'Volver al inicio',
    },
    scanned: {},
    scanner: {
      title: 'Escanea un texto',
      subtitle:
        'Etiqueta y visualiza el contenido de tu texto en relación con los objetivos de la Agenda 2030',
      info: `<p>
       <strong>¿Cómo funciona?</strong>
       Copia y pega el contenido del texto a analizar en la caja que se muestra a continuación o selecciona un archivo de tu ordenador. Una vez que lo tengas simplemente dale al botón de Escanear y disfruta de las visualizaciones automáticas que genera la herramienta.
      </p>
      <p>
      <strong>Escáner2030</strong>
      es una herramienta de uso gratuito y libre que te permite detectar y obtener visualizaciones de la presencia de los diferentes Objetivos de Desarrollo Sostenible (ODS) en cualquier texto.
      </p>`,
      form: {
        placeholder: 'Inserta aquí el texto que quieras escanear...',
        file: 'Sube un archivo',
        weight: 'El peso máximo soportado de los archivos es de 20 MB.',
        button: 'Escanear',
      },
    },
  },
};

export default messages;
